In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn import metrics
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as ols
from scipy import stats

In [2]:
df_train = pd.read_csv(r'C:\Users\sayanezio\Desktop\multiclass-classification-jaro\train.csv')

In [3]:
df_train.head()

ID  fixed acidity wine type  volatile acidity  citric acid  residual sugar  \
0   0            9.0     white              0.27         0.35             4.9   
1   1            7.1     white              0.36         0.37             4.8   
2   2            6.4     white              0.18         0.48             4.0   
3   3            6.7     white              0.33         0.49             1.6   
4   4            6.2     white              0.25         0.31             3.2   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.028                 27.0                  95.0  0.99320  3.04   
1      0.019                 39.0                 114.0  0.99036  3.08   
2      0.186                 64.0                 150.0  0.99450  3.06   
3      0.167                 20.0                  94.0  0.99140  3.11   
4      0.030                 32.0                 150.0  0.99014  3.18   

   sulphates  alcohol  quality  
0       0.40     11.3        6  
1       0.49     12.7        7  
2       0.40      9.3        5  
3       0.50     11.4        6  
4       0.31     12.0        6

In [4]:
df_train = df_train.drop(['ID'], axis = 'columns')

In [5]:
df_train.head()

fixed acidity wine type  volatile acidity  citric acid  residual sugar  \
0            9.0     white              0.27         0.35             4.9   
1            7.1     white              0.36         0.37             4.8   
2            6.4     white              0.18         0.48             4.0   
3            6.7     white              0.33         0.49             1.6   
4            6.2     white              0.25         0.31             3.2   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.028                 27.0                  95.0  0.99320  3.04   
1      0.019                 39.0                 114.0  0.99036  3.08   
2      0.186                 64.0                 150.0  0.99450  3.06   
3      0.167                 20.0                  94.0  0.99140  3.11   
4      0.030                 32.0                 150.0  0.99014  3.18   

   sulphates  alcohol  quality  
0       0.40     11.3        6  
1       0.49     12.7        7  
2       0.40      9.3        5  
3       0.50     11.4        6  
4       0.31     12.0        6

In [6]:
df_train.isnull().sum()

fixed acidity           0
wine type               0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [7]:
df_train.dtypes

fixed acidity           float64
wine type                object
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [8]:
df_dummy = pd.get_dummies(df_train['wine type'])

In [9]:
df_dummy.head()

red  white
0  False   True
1  False   True
2  False   True
3  False   True
4  False   True

In [10]:
df_train = pd.concat([df_train,df_dummy], axis = 1)

In [11]:
df_train.head()

fixed acidity wine type  volatile acidity  citric acid  residual sugar  \
0            9.0     white              0.27         0.35             4.9   
1            7.1     white              0.36         0.37             4.8   
2            6.4     white              0.18         0.48             4.0   
3            6.7     white              0.33         0.49             1.6   
4            6.2     white              0.25         0.31             3.2   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.028                 27.0                  95.0  0.99320  3.04   
1      0.019                 39.0                 114.0  0.99036  3.08   
2      0.186                 64.0                 150.0  0.99450  3.06   
3      0.167                 20.0                  94.0  0.99140  3.11   
4      0.030                 32.0                 150.0  0.99014  3.18   

   sulphates  alcohol  quality    red  white  
0       0.40     11.3        6  False   True  
1       0.49     12.7        7  False   True  
2       0.40      9.3        5  False   True  
3       0.50     11.4        6  False   True  
4       0.31     12.0        6  False   True

In [12]:
df_train = df_train.drop(['wine type'], axis =1)

In [13]:
df_train.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            9.0              0.27         0.35             4.9      0.028   
1            7.1              0.36         0.37             4.8      0.019   
2            6.4              0.18         0.48             4.0      0.186   
3            6.7              0.33         0.49             1.6      0.167   
4            6.2              0.25         0.31             3.2      0.030   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 27.0                  95.0  0.99320  3.04       0.40   
1                 39.0                 114.0  0.99036  3.08       0.49   
2                 64.0                 150.0  0.99450  3.06       0.40   
3                 20.0                  94.0  0.99140  3.11       0.50   
4                 32.0                 150.0  0.99014  3.18       0.31   

   alcohol  quality    red  white  
0     11.3        6  False   True  
1     12.7        7  False   True  
2      9.3        5  False   True  
3     11.4        6  False   True  
4     12.0        6  False   True

In [14]:
scaler = StandardScaler()

In [15]:
from sklearn.preprocessing import LabelEncoder
label_quality = LabelEncoder()

In [16]:
df_train.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            9.0              0.27         0.35             4.9      0.028   
1            7.1              0.36         0.37             4.8      0.019   
2            6.4              0.18         0.48             4.0      0.186   
3            6.7              0.33         0.49             1.6      0.167   
4            6.2              0.25         0.31             3.2      0.030   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 27.0                  95.0  0.99320  3.04       0.40   
1                 39.0                 114.0  0.99036  3.08       0.49   
2                 64.0                 150.0  0.99450  3.06       0.40   
3                 20.0                  94.0  0.99140  3.11       0.50   
4                 32.0                 150.0  0.99014  3.18       0.31   

   alcohol  quality    red  white  
0     11.3        6  False   True  
1     12.7        7  False   True  
2      9.3        5  False   True  
3     11.4        6  False   True  
4     12.0        6  False   True

In [17]:
df_train['quality'].value_counts()

quality
6    2136
5    1567
7     820
4     163
8     162
3      21
9       4
Name: count, dtype: int64

In [18]:
x = df_train.drop(['quality'], axis = 1).values

In [19]:
x

array([[9.0, 0.27, 0.35, ..., 11.3, False, True],
       [7.1, 0.36, 0.37, ..., 12.7, False, True],
       [6.4, 0.18, 0.48, ..., 9.3, False, True],
       ...,
       [6.6, 0.25, 0.41, ..., 10.2, False, True],
       [8.0, 0.48, 0.34, ..., 12.4, True, False],
       [7.5, 0.33, 0.39, ..., 9.4, False, True]], dtype=object)

In [20]:
y = df_train['quality'].values

In [21]:
y

array([6, 7, 5, ..., 7, 6, 5], dtype=int64)

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

model.fit(x_train, y_train)

In [23]:
scaler = StandardScaler()

In [24]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [25]:
x_train

array([[-1.08575429,  0.4709092 , -1.3126155 , ..., -0.01485882,
        -0.56885791,  0.56885791],
       [ 6.6027082 ,  0.13073627,  2.28816826, ...,  3.63711053,
         1.75790823, -1.75790823],
       [-0.62901395,  3.2541423 , -2.00507392, ...,  1.81112585,
         1.75790823, -1.75790823],
       ...,
       [ 0.28446675,  1.24402951, -2.07431976, ..., -0.09785812,
         1.75790823, -1.75790823],
       [ 0.13221996,  0.62553327, -0.82789461, ..., -1.25984837,
        -0.56885791,  0.56885791],
       [-0.02002682, -0.92070734,  0.48777638, ..., -0.01485882,
        -0.56885791,  0.56885791]])

In [26]:
x_test

array([[-0.72822903, -0.81668025,  1.86527449, ..., -0.4294533 ,
        -0.56827001,  0.56827001],
       [ 3.0000147 ,  0.75569652,  0.79949705, ...,  0.2410526 ,
         1.75972687, -1.75972687],
       [ 0.01741971, -0.11784613,  0.58634156, ..., -0.09420035,
        -0.56827001,  0.56827001],
       ...,
       [ 0.6802186 ,  2.73572654, -0.47943588, ..., -1.09995921,
         1.75972687, -1.75972687],
       [ 2.17151609, -0.17608231,  1.22580802, ..., -0.84851949,
        -0.56827001,  0.56827001],
       [-0.81107889, -0.7002079 , -0.12417674, ..., -0.84851949,
        -0.56827001,  0.56827001]])

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
model = RandomForestClassifier(n_estimators=200, random_state=0)

In [29]:
model.fit(x_train, y_train)
y_predict = model.predict(x_test)

In [30]:
y_predict

array([6, 6, 6, 5, 6, 7, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 5, 5, 6, 5, 6, 8,
       5, 5, 6, 6, 5, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 7,
       6, 5, 6, 6, 6, 7, 6, 7, 6, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 6, 6,
       7, 6, 6, 6, 6, 5, 8, 6, 6, 5, 6, 6, 5, 5, 5, 6, 5, 6, 5, 7, 5, 7,
       5, 5, 7, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 8, 6, 6, 6, 5, 5,
       7, 5, 6, 6, 6, 6, 6, 6, 6, 7, 6, 5, 5, 7, 5, 6, 5, 8, 6, 7, 5, 6,
       6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 5, 5, 8, 5, 6, 6, 6, 5, 6, 7, 6, 6,
       6, 5, 5, 6, 6, 6, 6, 6, 6, 7, 5, 5, 6, 6, 5, 5, 5, 7, 5, 6, 6, 6,
       6, 7, 6, 6, 6, 6, 7, 7, 6, 6, 6, 6, 6, 6, 7, 6, 5, 5, 6, 6, 5, 6,
       6, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 6, 5, 5, 5, 6, 6, 6, 5, 5, 5,
       5, 6, 6, 6, 7, 5, 6, 6, 6, 5, 6, 7, 5, 5, 5, 5, 5, 6, 6, 6, 6, 7,
       6, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 7, 6, 6, 5, 5, 6, 6, 6, 5,
       5, 6, 6, 5, 7, 6, 5, 6, 6, 6, 6, 6, 6, 6, 8, 6, 6, 7, 5, 6, 6, 6,
       6, 6, 6, 7, 6, 6, 6, 5, 6, 5, 5, 6, 6, 7, 6,

In [31]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         9
           4       1.00      0.10      0.18        31
           5       0.68      0.66      0.67       326
           6       0.61      0.78      0.68       420
           7       0.72      0.52      0.60       147
           8       0.87      0.31      0.46        42

    accuracy                           0.65       975
   macro avg       0.65      0.39      0.43       975
weighted avg       0.67      0.65      0.63       975



C:\Users\sayanezio\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sayanezio\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sayanezio\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
print(accuracy_score(y_test, y_predict))

0.6482051282051282


In [33]:
df_test = pd.read_csv(r'C:\Users\sayanezio\Desktop\multiclass-classification-jaro\test.csv')

In [34]:
df_test.head()

ID  fixed acidity wine type  volatile acidity  citric acid  residual sugar  \
0   0            7.4       red              0.66         0.00             1.8   
1   1            7.7       red              0.67         0.23             2.1   
2   2            6.9       red              0.55         0.15             2.2   
3   3            7.0       red              0.62         0.08             1.8   
4   4            7.6       red              0.90         0.06             2.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.075                 13.0                  40.0   0.9978  3.51   
1      0.088                 17.0                  96.0   0.9962  3.32   
2      0.076                 19.0                  40.0   0.9961  3.41   
3      0.076                  8.0                  24.0   0.9978  3.48   
4      0.079                  5.0                  10.0   0.9967  3.39   

   sulphates  alcohol  
0       0.56      9.4  
1       0.48      9.5  
2       0.59     10.1  
3       0.53      9.0  
4       0.56      9.8

In [35]:
df_test = df_test.drop(['ID'], axis = 'columns')

In [36]:
df_test.head()

fixed acidity wine type  volatile acidity  citric acid  residual sugar  \
0            7.4       red              0.66         0.00             1.8   
1            7.7       red              0.67         0.23             2.1   
2            6.9       red              0.55         0.15             2.2   
3            7.0       red              0.62         0.08             1.8   
4            7.6       red              0.90         0.06             2.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.075                 13.0                  40.0   0.9978  3.51   
1      0.088                 17.0                  96.0   0.9962  3.32   
2      0.076                 19.0                  40.0   0.9961  3.41   
3      0.076                  8.0                  24.0   0.9978  3.48   
4      0.079                  5.0                  10.0   0.9967  3.39   

   sulphates  alcohol  
0       0.56      9.4  
1       0.48      9.5  
2       0.59     10.1  
3       0.53      9.0  
4       0.56      9.8

In [37]:
df_dummy_test = pd.get_dummies(df_test['wine type'])

In [38]:
df_dummy_test

red  white
0      True  False
1      True  False
2      True  False
3      True  False
4      True  False
...     ...    ...
1013  False   True
1014  False   True
1015  False   True
1016  False   True
1017  False   True

[1018 rows x 2 columns]

In [39]:
df_test = pd.concat([df_test,df_dummy_test], axis = 1)

In [40]:
df_test.head()

fixed acidity wine type  volatile acidity  citric acid  residual sugar  \
0            7.4       red              0.66         0.00             1.8   
1            7.7       red              0.67         0.23             2.1   
2            6.9       red              0.55         0.15             2.2   
3            7.0       red              0.62         0.08             1.8   
4            7.6       red              0.90         0.06             2.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.075                 13.0                  40.0   0.9978  3.51   
1      0.088                 17.0                  96.0   0.9962  3.32   
2      0.076                 19.0                  40.0   0.9961  3.41   
3      0.076                  8.0                  24.0   0.9978  3.48   
4      0.079                  5.0                  10.0   0.9967  3.39   

   sulphates  alcohol   red  white  
0       0.56      9.4  True  False  
1       0.48      9.5  True  False  
2       0.59     10.1  True  False  
3       0.53      9.0  True  False  
4       0.56      9.8  True  False

In [41]:
df_test = df_test.drop(['wine type'], axis = 1)

In [42]:
df_test.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.66         0.00             1.8      0.075   
1            7.7              0.67         0.23             2.1      0.088   
2            6.9              0.55         0.15             2.2      0.076   
3            7.0              0.62         0.08             1.8      0.076   
4            7.6              0.90         0.06             2.5      0.079   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 13.0                  40.0   0.9978  3.51       0.56   
1                 17.0                  96.0   0.9962  3.32       0.48   
2                 19.0                  40.0   0.9961  3.41       0.59   
3                  8.0                  24.0   0.9978  3.48       0.53   
4                  5.0                  10.0   0.9967  3.39       0.56   

   alcohol   red  white  
0      9.4  True  False  
1      9.5  True  False  
2     10.1  True  False  
3      9.0  True  False  
4      9.8  True  False

In [43]:
test_x = df_test.values

In [44]:
test_x

array([[7.4, 0.66, 0.0, ..., 9.4, True, False],
       [7.7, 0.67, 0.23, ..., 9.5, True, False],
       [6.9, 0.55, 0.15, ..., 10.1, True, False],
       ...,
       [4.9, 0.235, 0.27, ..., 9.4, False, True],
       [5.7, 0.21, 0.32, ..., 10.6, False, True],
       [6.6, 0.32, 0.36, ..., 9.6, False, True]], dtype=object)

In [45]:
test_y_predict = model.predict(test_x)

test_y_predict

In [46]:
sub = df_test.index

In [47]:
test_y_predict.shape

(1018,)

In [48]:
sub.shape

(1018,)

In [49]:
submission_df = pd.DataFrame(list(zip(sub,test_y_predict)), columns = ['ID', 'quality'])
submission_df.head()

ID  quality
0   0        5
1   1        5
2   2        5
3   3        5
4   4        5

In [50]:
submission_df.to_csv(r"C:\Users\sayanezio\Desktop\multiclass-classification-jaro\submissionkaggleSayanKmulticlass.csv",index = False)